package com.example.chords2.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
////val Purple80 = Color(0xFFB6B6FF)
////val PurpleGrey80 = Color(0xFFB5D2E8)
////val Pink80 = Color(0xFF00FFE6)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
////val Purple40 = Color(0xFF8686C7)
////val PurpleGrey40 = Color(0xFF606E97)
////val Pink40 = Color(0xFF14C4AA)
//
//// Light / elevated tones
//// Core tones
//val Blue80 = Color(0xFFBBDEFB)       // light sky blue
//val BlueGrey80 = Color(0xFF90CAF9)   // soft blue
//val Cyan80 = Color(0xFF81D4FA)       // very light cyan-blue
//
//val Blue40 = Color(0xFF10439A)       // deep indigo-blue (primary)
//val BlueGrey40 = Color(0xFF446FAC)   // strong blue
//val Cyan40 = Color(0xFF00BCD4)       // vibrant cyan (accent)
//
//// Light containers - made more distinct from primary (lighter / more desaturated)
//val BluePrimaryContainerLight = Color(0xFF9AC8EA)    // medium light blue (distinct)
//val BlueSecondaryContainerLight = Color(0xFF85B8FF)  // very pale blue
//val BlueTertiaryContainerLight = Color(0xFFD3E3FF)   // pale cyan/teal
//
//// Dark containers - distinct shades (lighter or more muted than primary for elevation)
//val BluePrimaryContainerDark = Color(0xFF274D86)     // muted-lighter blue (contrast)
//val BlueSecondaryContainerDark = Color(0xFF1E5AA0)   // medium-dark blue
//val BlueTertiaryContainerDark = Color(0xFF00666A)

val primaryLight = Color(0xFF3D5F90)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD5E3FF)
val onPrimaryContainerLight = Color(0xFF234776)
val secondaryLight = Color(0xFF555F71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD9E3F8)
val onSecondaryContainerLight = Color(0xFF3D4758)
val tertiaryLight = Color(0xFF6E5676)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF7D8FF)
val onTertiaryContainerLight = Color(0xFF553F5D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF191C20)
val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3035)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFA6C8FF)
val surfaceDimLight = Color(0xFFD9DAE0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E8EE)
val surfaceContainerHighestLight = Color(0xFFE1E2E9)

val primaryDark = Color(0xFFA6C8FF)
val onPrimaryDark = Color(0xFF02315F)
val primaryContainerDark = Color(0xFF234776)
val onPrimaryContainerDark = Color(0xFFD5E3FF)
val secondaryDark = Color(0xFFBDC7DC)
val onSecondaryDark = Color(0xFF273141)
val secondaryContainerDark = Color(0xFF3D4758)
val onSecondaryContainerDark = Color(0xFFD9E3F8)
val tertiaryDark = Color(0xFFDABDE2)
val onTertiaryDark = Color(0xFF3D2846)
val tertiaryContainerDark = Color(0xFF553F5D)
val onTertiaryContainerDark = Color(0xFFF7D8FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE1E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE1E2E9)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFC4C6CF)
val outlineDark = Color(0xFF8D9199)
val outlineVariantDark = Color(0xFF43474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3035)
val inversePrimaryDark = Color(0xFF3D5F90)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF32353A)

